packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@antfu/eslint-config': 5.4.1
  '@babel/core': 7.28.4
  '@eslint-react/eslint-plugin': 1.53.1
  '@funboxteam/optimizt': 5.0.2
  '@next/env': 15.3.4
  '@next/eslint-plugin-next': 15.3.4
  '@pandacss/dev': 1.4.2
  '@pandacss/eslint-plugin': 0.2.14
  '@pandacss/preset-panda': 0.54.0
  '@playwright/test': 1.53.1
  '@radix-ui/colors': 3.0.0
  '@radix-ui/react-select': 2.2.6
  '@storybook/addon-a11y': 9.0.14
  '@storybook/addon-docs': 9.0.14
  '@storybook/addon-links': 9.0.14
  '@storybook/nextjs': 9.0.14
  '@storybook/test-runner': 0.23.0
  '@storybook/testing-library': 0.2.2
  '@t3-oss/env-nextjs': 0.13.8
  '@testing-library/react': 16.3.0
  '@types/node': 22.18.11
  '@types/react': 19.1.15
  '@types/react-dom': 19.1.9
  '@vercel/analytics': 1.5.0
  '@vitejs/plugin-react': 4.7.0
  autoprefixer: 10.4.21
  axe-playwright: 2.2.2
  bun-types: latest
  concurrently: 9.2.1
  critters: 0.0.25
  eslint: 9.37.0
  eslint-plugin-format: 1.0.2
  eslint-plugin-react-refresh: 0.4.23
  eslint-plugin-storybook: 9.0.14
  jsdom: 26.1.0
  lefthook: 1.13.6
  lucide-react: 0.545.0
  mdx: 0.3.1
  next: 15.4.4
  next-themes: 0.4.6
  pandacss-preset-radix-colors: 0.2.0
  patch-package: 8.0.1
  playwright: 1.53.1
  pncat: 0.6.1
  pnpm: 10.18.2
  postcss: 8.5.6
  prettier: 3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  recharts: 3.2.1
  storybook: 9.0.14
  tsup: 8.5.0
  turbo: 2.5.8
  typescript: 5.9.3
  vite: 7.0.6
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  webpack: 5.99.9
  zod: 4.0.10
