name: Build (Turbo)

on:
  - pull_request

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: moonrepo/setup-toolchain@v0
        with:
          # A GitHub action that sets up an environment for proto and moon.
          # - Installs proto globally so that installed tools can also be executed globally.
          # - Caches the toolchain (~/.proto) so subsequent runs are faster.
          # - Hashes .prototools and .moon/toolchain.yml files to generate a unique cache key.
          # - Cleans the toolchain before caching to remove unused or stale tools.
          # See: https://github.com/moonrepo/setup-toolchain
          auto-install: true

      - name: Get pnpm Store
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm Cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build dependencies with Turbo
        run: pnpm turbo build --filter='./packages/*'

      - name: Build web
        run: pnpm --filter web build
